#!/bin/bash

cd /var/www/html

# Run cron
su -s /usr/bin/php www-data cron.php

# Send activity emails
su -s /usr/bin/php www-data -- occ activity:send-mails

# Send event reminders
su -s /usr/bin/php www-data -- occ dav:send-event-reminders
